### PR TITLE
Bench: Use api/get/sites/user to populate site menu

### PR DESCRIPTION
**Pull request by ao-david**
This change removes the need to call get sites before every page load, allowing the loading to happen completely async.

This should limit the number of database calls before returning the page to the user. This should make cloudblue feel like it loads slightly faster

### CODE REVIEW

**Review by scruzin — APPROVED** [review]
LGTM, except `getUsersForSiteMenu` should probably just be renamed `getUserSites` (since it is now used via the API, and not necessarily for UI purposes).

Similarly, a function such as `getUserSites` should probably live in the `model` package.

**Comment by ao-david** [comment]
> LGTM, except `getUsersForSiteMenu` should probably just be renamed `getUserSites` (since it is now used via the API, and not necessarily for UI purposes).
> 
> Similarly, a function such as `getUserSites` should probably live in the `model` package.

Should I move the function to model, called `getUserSites` then call this from /api?

**Comment by scruzin** [comment]
> > LGTM, except `getUsersForSiteMenu` should probably just be renamed `getUserSites` (since it is now used via the API, and not necessarily for UI purposes).
> > Similarly, a function such as `getUserSites` should probably live in the `model` package.
> 
> Should I move the function to model, called `getUserSites` then call this from /api?

Yes, might as well do it now.

**Comment by ao-david** [comment]
> > > LGTM, except `getUsersForSiteMenu` should probably just be renamed `getUserSites` (since it is now used via the API, and not necessarily for UI purposes).
> > > Similarly, a function such as `getUserSites` should probably live in the `model` package.
> > 
> > 
> > Should I move the function to model, called `getUserSites` then call this from /api?
> 
> Yes, might as well do it now.

Done

**Review by scruzin — CHANGES_REQUESTED** [review]
Just use the email instead of the profile in GetUserSites.

**Comment by ao-david** [comment]
> Just use the email instead of the profile in GetUserSites.

Done

**Pull request merged**
