### PR TITLE
OceanCenter: Speaker v1.0.0 package

### PR DESCRIPTION
**Pull request by ao-david**
Add a package for speaker v1.0.0 containing:
    - v1.2.0 speaker
    - v1.0.0 audio.wav
    - v1.0.0 license.txt
    - v1.0.0 speaker.json
    - v1.0.0 run_pi_client.sh

### CODE REVIEW

**Review by scruzin — APPROVED** [review]
LGTM

**Comment by scruzin** [comment]
Okay to deploy to cloud @ao-david !

**Review by trekhopton — APPROVED** [review]

**Comment by scruzin** [comment]
run_pi_client.sh should be removed from the package (since it is now pre-installed).

**Review by scruzin — APPROVED** [review]
LGTM

**Pull request merged**
