### PR TITLE
ausoceantv: setup vite and lit for ausoceantv

### LINKED ISSUE #337: ausoceantv: Setup the front end files.
We should get a basic layout of files and folders in the ausoceantv directory that will support frontend development.

I propose we use Lit (typescript) for simple web components, and Vite for bundling and its blazing fast dev server.

### PR DESCRIPTION
**Pull request by trekhopton**
This was done as the first step in developing the frontend for ausoceantv. Vite was chosen for its amazing dev-server and bundling, and lit was chosen to be consistent with other ausocean projects in creating simple custom elements.

closes #337

### CODE REVIEW

**Review by ao-david — APPROVED** [review]
A screenshot of the index page would be a good addition to the PR, but otherwise LGTM

**Review by scott97 — APPROVED** [review]
LGTM :+1:

**Comment by ao-david** [comment]
Should there be a ```vite.config.js``` file?

**Comment by trekhopton** [comment]
image

**Comment by trekhopton** [comment]
> Should there be a `vite.config.js` file?

Everything is the default configuration at the moment so it's not needed but yes, we will likely need to add one soon.

**Pull request merged**
