### PR TITLE
Check Controller Status before starting hardware

### PR DESCRIPTION
**Pull request by ao-david**
Checking the controller status will prevent the hardware from trying to be started when the controller isn't connected. This will prevent a powered off rig from trying to start and will give a more informative error message.

We should still be adding testing for these functions.

### CODE REVIEW

**Comment by saxon-milton** [comment]
Is this a duplicate of #119

**Comment by saxon-milton** [comment]
> Is this a duplicate of #119 ?

Which one should we be looking at ?

**Comment by davidsutts** [comment]
> Is this a duplicate of #119 ?

Yes, not sure how that happened. Ignore this one.

**Comment by ao-david** [comment]
> > Is this a duplicate of #119 ?
> 
> Which one should we be looking at ?

Yes, not sure how this happened. Ignore this PR.

**Pull request closed without merging**
